<<<<<<< HEAD
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\admin\Desktop\LR2\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 331)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.conditionTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.conditionTextBrowser.setObjectName("conditionTextBrowser")
        self.gridLayout.addWidget(self.conditionTextBrowser, 0, 0, 1, 1)
        self.schemaLabel = QtWidgets.QLabel(self.centralwidget)
        self.schemaLabel.setObjectName("schemaLabel")
        self.gridLayout.addWidget(self.schemaLabel, 1, 0, 1, 1)
        self.formulaLabel = QtWidgets.QLabel(self.centralwidget)
        self.formulaLabel.setObjectName("formulaLabel")
        self.gridLayout.addWidget(self.formulaLabel, 2, 0, 1, 1)
        self.probabilityTable = QtWidgets.QTableWidget(self.centralwidget)
        self.probabilityTable.setMinimumSize(QtCore.QSize(811, 51))
        self.probabilityTable.setMaximumSize(QtCore.QSize(16777215, 51))
        self.probabilityTable.setObjectName("probabilityTable")
        self.probabilityTable.setColumnCount(6)
        self.probabilityTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.probabilityTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.probabilityTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.probabilityTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.probabilityTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.probabilityTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.probabilityTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.probabilityTable.setHorizontalHeaderItem(5, item)
        self.gridLayout.addWidget(self.probabilityTable, 3, 0, 1, 1)
        self.resultTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.resultTextEdit.setObjectName("resultTextEdit")
        self.gridLayout.addWidget(self.resultTextEdit, 4, 0, 1, 1)
        self.calcButton = QtWidgets.QPushButton(self.centralwidget)
        self.calcButton.setObjectName("calcButton")
        self.gridLayout.addWidget(self.calcButton, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ТерВер ЛР-2 3 вар. №1"))
        self.conditionTextBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Найти вероятность отказа схемы, приведённой на рисунке, предполагая, что отказы отдельных элементов независимы и равны соответственно q</span><span style=\" font-size:9pt; vertical-align:sub;\">i</span></p></body></html>"))
        self.schemaLabel.setText(_translate("MainWindow", "TextLabel"))
        self.formulaLabel.setText(_translate("MainWindow", "TextLabel"))
        item = self.probabilityTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Вероятность отказа элемента [0; 1]"))
        item = self.probabilityTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.probabilityTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.probabilityTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.probabilityTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.probabilityTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.probabilityTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        self.calcButton.setText(_translate("MainWindow", "Вычислить"))
=======
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\admin\Desktop\LR2\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 331)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.conditionTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.conditionTextBrowser.setObjectName("conditionTextBrowser")
        self.gridLayout.addWidget(self.conditionTextBrowser, 0, 0, 1, 1)
        self.schemaLabel = QtWidgets.QLabel(self.centralwidget)
        self.schemaLabel.setObjectName("schemaLabel")
        self.gridLayout.addWidget(self.schemaLabel, 1, 0, 1, 1)
        self.formulaLabel = QtWidgets.QLabel(self.centralwidget)
        self.formulaLabel.setObjectName("formulaLabel")
        self.gridLayout.addWidget(self.formulaLabel, 2, 0, 1, 1)
        self.probabilityTable = QtWidgets.QTableWidget(self.centralwidget)
        self.probabilityTable.setMinimumSize(QtCore.QSize(811, 51))
        self.probabilityTable.setMaximumSize(QtCore.QSize(16777215, 51))
        self.probabilityTable.setObjectName("probabilityTable")
        self.probabilityTable.setColumnCount(6)
        self.probabilityTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.probabilityTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.probabilityTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.probabilityTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.probabilityTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.probabilityTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.probabilityTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.probabilityTable.setHorizontalHeaderItem(5, item)
        self.gridLayout.addWidget(self.probabilityTable, 3, 0, 1, 1)
        self.resultTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.resultTextEdit.setObjectName("resultTextEdit")
        self.gridLayout.addWidget(self.resultTextEdit, 4, 0, 1, 1)
        self.calcButton = QtWidgets.QPushButton(self.centralwidget)
        self.calcButton.setObjectName("calcButton")
        self.gridLayout.addWidget(self.calcButton, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ТерВер ЛР-2 3 вар. №1"))
        self.conditionTextBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Найти вероятность отказа схемы, приведённой на рисунке, предполагая, что отказы отдельных элементов независимы и равны соответственно q</span><span style=\" font-size:9pt; vertical-align:sub;\">i</span></p></body></html>"))
        self.schemaLabel.setText(_translate("MainWindow", "TextLabel"))
        self.formulaLabel.setText(_translate("MainWindow", "TextLabel"))
        item = self.probabilityTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Вероятность отказа элемента [0; 1]"))
        item = self.probabilityTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.probabilityTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.probabilityTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.probabilityTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.probabilityTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.probabilityTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        self.calcButton.setText(_translate("MainWindow", "Вычислить"))
>>>>>>> 18294e9de50f832036c408dfa4b24bea2a46a6bf
